server:
  port: 9000

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/user_db?user=root&password=000000&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
wechat:
  mpAppId:
  mpAppSecret:

#mysql
spring:
  application:
    name: springteam-21922
  redis:
    host: 127.0.0.1
    pool: 6379
  datasource:
    url: jdbc:mysql://rm-bp1014ie345y164lbho.mysql.rds.aliyuncs.com:3306/springteam-21922?user=root&password=Zhzhw2816&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 000000
    driver-class-name: com.mysql.cj.jdbc.Driver
#com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  liquibase:
    change-log: classpath:liquibase/master.xml
    drop-first: false
    enabled: true
#mybatis-plus
mybatis-plus:
  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:user/persistence/*.xml
#  base-package: com.lxbb.user.user.persistence
#  mapper-locations: classpath:com/lxbb/user/**/persistence/*.class
#  type-aliases-package: com.lxbb.user.**.domain
#  mapper-locations: classpath:com/lxbb/user/**/persistence/*.xml

#  type-handlers-package
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
        #驼峰下划线转换
      column-underline: true
        #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9100/eureka/
#    instance:
#      prefer-ip-address: true

